spring:
  data:
    redis:
      username: default
      password: 1234
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.esgsurqbjnaustmcaqbf
    password: hoit1000llm
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 99898080219-t1blduds15lqb1lt5a5p13p07jsjlf6f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            user-name-attribute: sub
jwt:
  key: afsdkfkjvnxkczjhiafoauw235iu3y64h5tlknfiaidhsfjkasfkjnvsdkjvbagh9y573wytgjierhfgkdsjgjf
  refresh-token:
    expire-time: 604800000