app:
  client:
    url: http://localhost:8090
server:
  port: 8090
  shutdown: graceful
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  config:
    activate:
      on-profile: default
    import: "application-secret.yml"
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8090/auth/google/redirect
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
